In [5]:
import numpy as np


In [3]:
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [7]:
c=np.array([(1,2,3),(4,5,6)])

In [8]:
print(c)

[[1 2 3]
 [4 5 6]]


In [10]:
trans=np.transpose(c)

In [11]:
print (trans)

[[1 4]
 [2 5]
 [3 6]]


In [3]:
vicky.ravel()

NameError: name 'vicky' is not defined

In [16]:
a.reshape(3,1)

array([[1],
       [2],
       [3]])

In [18]:
 ze=np.zeros((3,3))

In [19]:
print(ze)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
one=np.ones((3,3))

In [7]:
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
